<?php
namespace App\Utility;

class TMenuUtility
{
    public static function getIcon($iconName, $times=1, $default=null)
    {
        $icon = TArrayUtility::getValue(self::ICONS, $iconName, $default);
        if( $icon != null )
        {
            return self::FONT_PREFIX . $icon . sprintf(' fa-%dx', $times);  //self::FONT_POSTFIX;
        }
        return 'fa fa-dashboard fa-3x';
    }

    //http://fontawesome.io/icons/
    const FONT_PREFIX = 'fa ';
    const FONT_POSTFIX = ' fa-3x';
    const ICONS = array(
        'address_book' => 'fa-address-book',
        'address_card' => 'fa-address-card',
        'adjust' => 'fa-adjust',
        'anchor' => 'fa-anchor',
        'area_chart' => 'fa-area-chart',
        
        'balance_scale' => 'fa-balance-scale',
        'university' => 'fa-university',
        'bar_chart' => 'fa-bar-chart',
        'barcode' => 'fa-barcode',
        'bars' => 'fa-bars',
        'battery0' => 'fa-battery-empty',
        'battery1' => 'fa-battery-quarter',
        'battery2' => 'fa-battery-half',
        'battery3' => 'fa-battery-three-quarters',
        'battery4' => 'fa-battery-full',
        'bed' => 'fa-bed',
        'beer' => 'fa-beer',
        'bell' => 'fa-bell',
        'bell_slash' => 'fa-bell-slash',
        'birthday-cake' => 'fa-birthday-cake',
        'bluetooth' => 'fa-bluetooth',
        'bolt' => 'fa-bolt',
        'bomb' => 'fa-bomb',
        'book' => 'fa-book',
        'bookmark' => 'fa-bookmark',
        'briefcase' => 'fa-briefcase',
        'bug' => 'fa-bug',
        'building' => 'fa-building',
        'bullhorn' => 'fa-bullhorn',
        'bullseye' => 'fa-bullseye',
        
        'calculator' => 'fa-calculator',
        'calendar' => 'fa-calendar',
        'calendar_o' => 'fa-calendar-o',
        'camera' => 'fa-camera',
        'caret_down' => 'fa-caret-square-o-down',
        'caret_left' => 'fa-caret-square-o-left',
        'caret_right' => 'fa-caret-square-o-right',
        'caret_up' => 'fa-caret-square-o-up',
        'cart_arrow_down' => 'fa-cart-arrow-down',
        'cart_plus' => 'fa-cart-plus',
        'certificate' => 'fa-certificate',
        'check' => 'fa-check',
        'check_circle' => 'fa-check-circle',
        'check_square' => 'fa-check-square',
        'child' => 'fa-child',
        'circle' => 'fa-circle',
        'circle_notch' => 'fa-circle-o-notch',
        'clock' => 'fa-clock-o',
        'clone' => 'fa-clone',
        'times' => 'fa-times',
        'cloud' => 'fa-cloud',
        'code' => 'fa-code',
        'code_fork' => 'fa-code-fork',
        'coffee' => 'fa-coffee',
        'cog' => 'fa-cog',
        'cogs' => 'fa-cogs',
        'comment' => 'fa-comment',
        'commenting' => 'fa-commenting',
        'comments' => 'fa-comments',
        'credit_card' => 'fa-credit-card',
        'crop' => 'fa-crop',
        'cube' => 'fa-cube',
        'cutlery' => 'fa-cutlery',
        
        'dashboard' => 'fa-dashboard',  //'fa-tachometer',
        'database' => 'fa-database',
        'desktop' => 'fa-desktop',
        'dot_circle' => 'fa-dot-circle-o',
        'download' => 'fa-download',
        
        'edit' => 'fa-pencil-square-o',
        'ellipsis' => 'fa-ellipsis-h',
        'envelope' => 'fa-envelope',
        'envelope_open' => 'fa-envelope-open',
        'eraser' => 'fa-eraser',
        'exchange' => 'fa-exchange',
        'exclamation' => 'fa-exclamation',
        'exclamation_circle' => 'fa-exclamation-circle',
        'exclamation_triangle' => 'fa-exclamation-triangle',
        'eye' => 'fa-eye',
        'eyedropper' => 'fa-eyedropper',
        
        'fax' => 'fa-fax',
        'rss' => 'fa-rss',
        'female' => 'fa-female',
        'film' => 'fa-film',
        'filter' => 'fa-filter',
        'fire' => 'fa-fire',
        'fire_extinguisher' => 'fa-fire-extinguisher',
        'flag' => 'fa-flag',
        'flask' => 'fa-flask',
        'folder' => 'fa-folder',
        'folder_open' => 'fa-folder-open',
        'frown' => 'fa-frown-o',
        'futbol' => 'fa-futbol-o',
        
        'gamepad' => 'fa-gamepad',
        'gavel' => 'fa-gavel',
        'gear' => 'fa-cog',
        'gears' => 'fa-cogs',
        'gift' => 'fa-gift',
        'glass' => 'fa-glass',
        'globe' => 'fa-globe',
        'graduation_cap' => 'fa-graduation-cap',
        'group' => 'fa-users',
        
        'handshake' => 'fa-handshake-o',
        'hashtag' => 'fa-hashtag',
        'hdd' => 'fa-hdd-o',
        'headphones' => 'fa-headphones',
        'heart' => 'fa-heart',
        'heartbeat' => 'fa-heartbeat',
        'history' => 'fa-history',
        'home' => 'fa-home',
        
        'id_card' => 'fa-id-card',
        'inbox' => 'fa-inbox',
        'info' => 'fa-info',
        'info_circle' => 'fa-info-circle',
        
        'key' => 'fa-key',
        'keyboard' => 'fa-keyboard-o',
        
        'language' => 'fa-language',
        'laptop' => 'fa-laptop',
        'leaf' => 'fa-leaf',
        'lightbulb' => 'fa-lightbulb-o',
        'line_chart' => 'fa-line-chart',
        'lock' => 'fa-lock',
        
        'magic' => 'fa-magic',
        'magnet' => 'fa-magnet',
        'male' => 'fa-male',
        'map' => 'fa-map',
        'map_marker' => 'fa-map-marker',
        'map_pin' => 'fa-map-pin',
        'map_signs' => 'fa-map-signs',
        'microphone' => 'fa-microphone',
        'microphone_slash' => 'fa-microphone-slash',
        'minus' => 'fa-minus',
        'minus_circle' => 'fa-minus-circle',
        'minus_square' => 'fa-minus-square',
        'mobile' => 'fa-mobile',
        'money' => 'fa-money',
        'moon_o' => 'fa-moon-o',
        'music' => 'fa-music',
        
        'newspaper_o' => 'fa-newspaper-o',
        
        'object_group' => 'fa-object-group',
        'object_ungroup' => 'fa-object-ungroup',
        
        'paint_brush' => 'fa-paint-brush',
        'paper_plane' => 'fa-paper-plane',
        'paper_plane-o' => 'fa-paper-plane-o',
        'paw' => 'fa-paw',
        'pencil' => 'fa-pencil',
        'pencil_square' => 'fa-pencil-square',
        'pencil_square-o' => 'fa-pencil-square-o',
        'percent' => 'fa-percent',
        'phone' => 'fa-phone',
        'phone_square' => 'fa-phone-square',
        'picture' => 'fa-picture-o',
        'pie_chart' => 'fa-pie-chart',
        'plane' => 'fa-plane',
        'plug' => 'fa-plug',
        'plus' => 'fa-plus',
        'plus_circle' => 'fa-plus-circle',
        'plus_square' => 'fa-plus-square',
        'plus_square-o' => 'fa-plus-square-o',
        'podcast' => 'fa-podcast',
        'power_off' => 'fa-power-off',
        'print' => 'fa-print',
        'puzzle_piece' => 'fa-puzzle-piece',
        
        'qrcode' => 'fa-qrcode',
        'question' => 'fa-question',
        'question_circle' => 'fa-question-circle',
        'question_circle-o' => 'fa-question-circle-o',
        'quote_left' => 'fa-quote-left',
        'quote_right' => 'fa-quote-right',
        
        'random' => 'fa-random',
        'recycle' => 'fa-recycle',
        'refresh' => 'fa-refresh',
        'registered' => 'fa-registered',
        'reply' => 'fa-reply',
        'reply_all' => 'fa-reply-all',
        'retweet' => 'fa-retweet',
        'road' => 'fa-road',
        'rocket' => 'fa-rocket',
        'rss' => 'fa-rss',
        'rss_square' => 'fa-rss-square',
        
        'search' => 'fa-search',
        'search_minus' => 'fa-search-minus',
        'search-plus' => 'fa-search-plus',
        'server' => 'fa-server',
        'share' => 'fa-share',
        'share_alt' => 'fa-share-alt',
        'share_alt_square' => 'fa-share-alt-square',
        'share_square' => 'fa-share-square',
        'share_square_o' => 'fa-share-square-o',
        'shield' => 'fa-shield',
        'ship' => 'fa-ship',
        'shopping_bag' => 'fa-shopping-bag',
        'shopping_basket' => 'fa-shopping-basket',
        'shopping_cart' => 'fa-shopping-cart',
        'shower' => 'fa-shower',
        'sign_in' => 'fa-sign-in',
        'sign_language' => 'fa-sign-language',
        'sign_out' => 'fa-sign-out',
        'signal' => 'fa-signal',
        'sitemap' => 'fa-sitemap',
        'sliders' => 'fa-sliders',
        'smile_o' => 'fa-smile-o',
        'snowflake-o' => 'fa-snowflake-o',
        'sort' => 'fa-sort',
        'sort_alpha_asc' => 'fa-sort-alpha-asc',
        'sort_alpha_desc' => 'fa-sort-alpha-desc',
        'sort_amount_asc' => 'fa-sort-amount-asc',
        'sort_amount_desc' => 'fa-sort-amount-desc',
        'sort_asc' => 'fa-sort-asc',
        'sort_desc' => 'fa-sort-desc',
        'sort_numeric_asc' => 'fa-sort-numeric-asc',
        'sort_numeric_desc' => 'fa-sort-numeric-desc',
        'space_shuttle' => 'fa-space-shuttle',
        'spinner' => 'fa-spinner',
        'spoon' => 'fa-spoon',
        'square' => 'fa-square',
        'square_o' => 'fa-square-o',
        'star' => 'fa-star',
        'star_half' => 'fa-star-half',
        'star_half_o' => 'fa-star-half-o',
        'star_o' => 'fa-star-o',
        'sticky_note' => 'fa-sticky-note',
        'sticky_note_o' => 'fa-sticky-note-o',
        'street_view' => 'fa-street-view',
        'suitcase' => 'fa-suitcase',
        'sun_o' => 'fa-sun-o',
        
        'tablet' => 'fa-tablet',
        'tag' => 'fa-tag',
        'tags' => 'fa-tags',
        'tasks' => 'fa-tasks',
        'taxi' => 'fa-taxi',
        'television' => 'fa-television',
        'terminal' => 'fa-terminal',
        'thumb_tack' => 'fa-thumb-tack',
        'thumbs_down' => 'fa-thumbs-down',
        'thumbs_o_down' => 'fa-thumbs-o-down',
        'thumbs_o_up' => 'fa-thumbs-o-up',
        'thumbs_up' => 'fa-thumbs-up',
        'ticket' => 'fa-ticket',
        'times' => 'fa-times',
        'times_circle' => 'fa-times-circle',
        'times_circle_o' => 'fa-times-circle-o',
        'tint' => 'fa-tint',
        'toggle_off' => 'fa-toggle-off',
        'toggle_on' => 'fa-toggle-on',
        'trademark' => 'fa-trademark',
        'trash' => 'fa-trash',
        'trash_o' => 'fa-trash-o',
        'tree' => 'fa-tree',
        'trophy' => 'fa-trophy',
        'truck' => 'fa-truck',
        'tty' => 'fa-tty',
        
        'umbrella' => 'fa-umbrella',
        'universal_access' => 'fa-universal-access',
        'university' => 'fa-university',
        'unlock' => 'fa-unlock',
        'unlock_alt' => 'fa-unlock-alt',
        'upload' => 'fa-upload',
        'user' => 'fa-user',
        'user_circle' => 'fa-user-circle',
        'user_circle_o' => 'fa-user-circle-o',
        'user_o' => 'fa-user-o',
        'user_plus' => 'fa-user-plus',
        'user_secret' => 'fa-user-secret',
        'user_times' => 'fa-user-times',
        'users', 'fa-users',
        
        'video_camera' => 'fa-video-camera',
        'volume_control_phone' => 'fa-volume-control-phone',
        'volume_down' => 'fa-volume-down',
        'volume_off' => 'fa-volume-off',
        'volume_up' => 'fa-volume-up',
        
        'wheelchair' => 'fa-wheelchair',
        'wheelchair_alt' => 'fa-wheelchair-alt',
        'wifi' => 'fa-wifi',
        'window_close' => 'fa-window-close',
        'window_close_o' => 'fa-window-close-o',
        'window_maximize' => 'fa-window-maximize',
        'window_minimize' => 'fa-window-minimize',
        'window_restore' => 'fa-window-restore',
        'wrench' => 'fa-wrench'
        
        // Example of registered
    );
}